### ISSUE TITLE
"415 Unsupported Media Type" Error bei fehlendem Content-Type

### ISSUE THREAD

**Issue by Art4** [youthweb/youthweb-api#13]
[JSON API](http://jsonapi.org/format/#content-negotiation) verlangt, dass der Client und Server die Header `Content-Type: application/vnd.api+json` angeben. Es muss ein `415 Unsupported Media Type ` Error zurückgegeben werden, wenn der Client den Content-Type nicht angegeben hat.

**Comment by mwiens** [comment]
*english version below*

Vielen Dank für Ihre Nachricht!

Ich bin bis zum 30.08.2015 im Urlaub und ab dem 31.08.2015 wieder erreichbar. Ihre Nachricht wird nicht weitergeleitet aber nach dem Urlaub auf jeden Fall bearbeitet. Vielen Dank für Ihre Geduld!

Mit besten Grüßen

Maximilian WIens

-diese Nachricht wurde automatisch generiert-
--8<-----------------------------------

Thank you for the message!

I am on vacation until 30.08.2015 and will be available from 31.08.2015. Your message will be not forwarded, but I will read your mail in any case after the vacation. Thank you for your patience!

With best regards

Maximilian Wiens

-this is a automatically generated message-
